
---CREATING DATABASE

CREATE  DATABASE JOBS;

---CREATE DEPRATMENT TABLE

CREATE TABLE DEPARTMENT
(
DEP_ID INT IDENTITY (1,1) PRIMARY KEY,
DEP_NAME VARCHAR(50)
)


----CREATE EMPLOYEES TABLE

CREATE TABLE EMPLOYEES 
(
EMP_ID INT IDENTITY (1,1) PRIMARY KEY,
EMP_NAME VARCHAR(50),
EMP_DEP INT,
SALARY INT,
PHONE VARCHAR(20),
LOCATION VARCHAR(50),
FOREIGN KEY(EMP_DEP) REFERENCES DEPARTMENT(DEP_ID)
);

